config-version = 2
start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

focus-follows-mouse.enabled = false

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-window-detected = [
    { if = 'test %{app-bundle-id} = net.kovidgoyal.kitty', run = 'move-node-to-workspace 1' },
    { if = 'test %{app-bundle-id} = com.microsoft.VSCode', run = 'move-node-to-workspace 2' },
    { if = 'test %{app-bundle-id} = com.brave.Browser', run = 'move-node-to-workspace 3' },
    { if = 'test %{app-bundle-id} = com.brave.Browser.beta', run = 'move-node-to-workspace 3' },
]

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'

ctrl-h = 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

ctrl-minus = 'resize smart -50'
ctrl-equal = 'resize smart +50'

ctrl-slash = 'layout tiles horizontal vertical'
ctrl-space = 'layout tiles horizontal vertical'
ctrl-f = 'fullscreen'
ctrl-w = 'close'
ctrl-t = 'layout floating tiling'
ctrl-shift-r = 'reload-config'
ctrl-tab = 'workspace-back-and-forth'

ctrl-enter = "exec-and-forget open -na kitty"
ctrl-v = "exec-and-forget open -na 'Visual Studio Code'"
ctrl-b = "exec-and-forget open -na 'Brave Browser'"
ctrl-shift-b = "exec-and-forget open -na 'Brave Browser Beta'"
