#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/globalstyles.sh"

POPUP_OFF="sketchybar --set \$NAME popup.drawing=off"

sketchybar --bar "${bar[@]}" --default "${item_defaults[@]}"

sketchybar --add event aerospace_workspace_change

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/xscriptor.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/datetime.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/stats.sh"

sketchybar --add bracket left.side '/space\..*/' \
  --set left.side "${bracket_defaults[@]}"

sketchybar --add bracket right.side date clock wifi volume_icon volume battery brew stats \
  --set right.side "${bracket_defaults[@]}"

sketchybar --update
